with-expecter: true
resolve-type-alias: false
disable-version-string: true
quiet: false
dir: "mocks"
outpkg: "mocks"
issue-845-fix: true
packages:
  go.fork.vn/redis:
    interfaces:
      Manager:
        config:
          recursive: true
all: false