// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	di "go.fork.vn/di"
)

// MockServiceProvider is an autogenerated mock type for the ServiceProvider type
type MockServiceProvider struct {
	mock.Mock
}

type MockServiceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceProvider) EXPECT() *MockServiceProvider_Expecter {
	return &MockServiceProvider_Expecter{mock: &_m.Mock}
}

// Boot provides a mock function with given fields: app
func (_m *MockServiceProvider) Boot(app di.Application) {
	_m.Called(app)
}

// MockServiceProvider_Boot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Boot'
type MockServiceProvider_Boot_Call struct {
	*mock.Call
}

// Boot is a helper method to define mock.On call
//   - app di.Application
func (_e *MockServiceProvider_Expecter) Boot(app interface{}) *MockServiceProvider_Boot_Call {
	return &MockServiceProvider_Boot_Call{Call: _e.mock.On("Boot", app)}
}

func (_c *MockServiceProvider_Boot_Call) Run(run func(app di.Application)) *MockServiceProvider_Boot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(di.Application))
	})
	return _c
}

func (_c *MockServiceProvider_Boot_Call) Return() *MockServiceProvider_Boot_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceProvider_Boot_Call) RunAndReturn(run func(di.Application)) *MockServiceProvider_Boot_Call {
	_c.Run(run)
	return _c
}

// Providers provides a mock function with no fields
func (_m *MockServiceProvider) Providers() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Providers")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockServiceProvider_Providers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Providers'
type MockServiceProvider_Providers_Call struct {
	*mock.Call
}

// Providers is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) Providers() *MockServiceProvider_Providers_Call {
	return &MockServiceProvider_Providers_Call{Call: _e.mock.On("Providers")}
}

func (_c *MockServiceProvider_Providers_Call) Run(run func()) *MockServiceProvider_Providers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_Providers_Call) Return(_a0 []string) *MockServiceProvider_Providers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_Providers_Call) RunAndReturn(run func() []string) *MockServiceProvider_Providers_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: app
func (_m *MockServiceProvider) Register(app di.Application) {
	_m.Called(app)
}

// MockServiceProvider_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockServiceProvider_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - app di.Application
func (_e *MockServiceProvider_Expecter) Register(app interface{}) *MockServiceProvider_Register_Call {
	return &MockServiceProvider_Register_Call{Call: _e.mock.On("Register", app)}
}

func (_c *MockServiceProvider_Register_Call) Run(run func(app di.Application)) *MockServiceProvider_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(di.Application))
	})
	return _c
}

func (_c *MockServiceProvider_Register_Call) Return() *MockServiceProvider_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServiceProvider_Register_Call) RunAndReturn(run func(di.Application)) *MockServiceProvider_Register_Call {
	_c.Run(run)
	return _c
}

// Requires provides a mock function with no fields
func (_m *MockServiceProvider) Requires() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Requires")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockServiceProvider_Requires_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Requires'
type MockServiceProvider_Requires_Call struct {
	*mock.Call
}

// Requires is a helper method to define mock.On call
func (_e *MockServiceProvider_Expecter) Requires() *MockServiceProvider_Requires_Call {
	return &MockServiceProvider_Requires_Call{Call: _e.mock.On("Requires")}
}

func (_c *MockServiceProvider_Requires_Call) Run(run func()) *MockServiceProvider_Requires_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceProvider_Requires_Call) Return(_a0 []string) *MockServiceProvider_Requires_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceProvider_Requires_Call) RunAndReturn(run func() []string) *MockServiceProvider_Requires_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceProvider creates a new instance of MockServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceProvider {
	mock := &MockServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
